services:
  mariadb:
    image: mariadb:latest
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - type: volume
        source: dbVG
        target: /var/lib/mysql
    ports:
      - 3305:3306
  php:
    build: 
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - type: volume
        source: tls
        target: /root/.symfony5/certs
      - type: volume
        target: /app/vendor
      - type: bind
        source: .
        target: /app
    depends_on:
      - mariadb
    ports:
      - 8000:8000
  encore:
    build:
      context: .
      dockerfile: Dockerfile.encore.dev
    volumes:
      - type: volume
        source: tls
        target: /root/.symfony5/certs
      - type: volume
        target: /app/node_modules
      - type: bind
        source: .
        target: /app
  mail:
    image: mailhog/mailhog
    ports: 
      - 8025:8025
volumes:
  dbVG:
  tls: